services:
  - type: web
    name: tricore-data-media
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: APP_NAME
        value: "TRICORE DATA MEDIA"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
